### PR TITLE
chore: update MermaidJS to v10.8.0

### LINKED ISSUE #90: Update mermaid
The current version is pretty old.  Please :)

### PR DESCRIPTION
**Pull request by oneWaveAdrian**
Closes #90 

## Changelog

- chore: updates MermaidJS to [v10.8.0](https://github.com/mermaid-js/mermaid/releases/tag/v10.8.0)
- chore: updates yarn.lock to fix expired certificates
- doc: update Mermaid Version in Readme

### CODE REVIEW

**Comment by oneWaveAdrian** [comment]
@shd101wyy Would be great if you could give this a review. 

I am not certain what the next steps are to get the [VSCode Markdown Preview](https://github.com/shd101wyy/vscode-markdown-preview-enhanced) to support Mermaid `10.8.0` as well, looks like I could open another PR there with the updated Crossnotes dependency?

Let me know if I can help you out somehow! Really appreciate all the hard work that went into this, thank you!

**Comment by oneWaveAdrian** [comment]
@shd101wyy bump 🙃

**Comment by shd101wyy** [comment]
Hi @oneWaveAdrian , thank you for the PR.

https://github.com/shd101wyy/crossnote/blob/b64a355d496a6380f61bd76473f7b1f691bbafe5/src/markdown-engine/index.ts#L815 This line might need to be changed to match the `10.8.0` version.  

Also, the file located in https://github.com/shd101wyy/crossnote/tree/develop/dependencies/mermaid needs to be manually replaced.

```
wget https://cdn.jsdelivr.net/npm/mermaid@10.8.0/dist/mermaid.min.js
```

:+1:

**Review by shd101wyy — CHANGES_REQUESTED** [review]
I left a comment above ^^^ Thank you!

**Comment by oneWaveAdrian** [comment]
@shd101wyy Thanks for the review! Exchanged all files. Additionally fixed linter warnings flagged by CI, shouldn't have failed it though.

Regarding the manual copy task for locally hosted scripts such as mermaid. I wonder if a script running post npm-build that copies the files from `node_modules` to the respective folder would do the trick? Or else a CI step with auto commit?

**Review by shd101wyy — APPROVED** [review]
LGTM :+1: Thank you for updating mermaid.js and fixing the CI.  
It seems like mermaid 10.9.0 just released. I will update it accordingly afterwards.  
Of course it will be great if we can have a script for automatically download all the scripts :+1:

**Pull request merged**
